name: calculadora_final
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependência padrão do Flutter para ícones de estilo iOS.
  cupertino_icons: ^1.0.8
  
  # ✅ PACOTE ADICIONADO para resolver as contas da calculadora.
  math_expressions: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Ferramenta para ajudar a escrever um código Dart mais limpo.
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # Para adicionar assets (imagens), descomente as linhas abaixo.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para adicionar fontes customizadas, descomente as linhas abaixo.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
